import Head from "next/head";
import ChatListItem from "@/components/chat-list-item";
import Chat from "@/components/chat";

export default function Home() {
  return (
    <>
      <Head>
        <title>Pigeon</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        <div className="chats">
          <div className="chat-header">
            <h2 className="chat-header-info">Chats</h2>
            <div className="chat-header-icon chat-header-avatar"></div>
          </div>
          <div className="chat-list">
            {new Array(100).fill(0).map((chatListItem, i) => (
              <ChatListItem key={i} />
            ))}
          </div>
        </div>
        <Chat />
      </div>
    </>
  );
}
