import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Pigeon</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        <div className="chats">
          <div className="chat-header">
            <div className="chat-header-avatar"></div>

            <div className="chat-header-info-name">Chats</div>
            <div className="chat-header-avatar"></div>
          </div>
        </div>
        <div className="chat">
          <div className="chat-header"></div>
        </div>
      </div>
    </>
  );
}
